# Generated by Django 3.0.8 on 2020-08-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='项目名')),
                ('leader', models.CharField(max_length=50, unique=True, verbose_name='负责人')),
                ('tester', models.CharField(max_length=50, verbose_name='测试人员')),
                ('programer', models.CharField(max_length=50, verbose_name='开发人员')),
                ('publish_app', models.CharField(max_length=50, verbose_name='应用名称')),
                ('desc', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='简要描述')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'db_table': 'lx_projects',
            },
        ),
    ]
