# Generated by Django 3.0.8 on 2020-08-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='leader',
            field=models.CharField(max_length=50, verbose_name='负责人'),
        ),
    ]
