# Generated by Django 3.0.8 on 2020-07-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=16, unique=True)),
                ('jobnumber', models.CharField(max_length=16)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=16, unique=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tp_employees',
            },
        ),
    ]
