# Generated by Django 3.0.8 on 2020-07-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='ename',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='employees',
            name='jobnumber',
            field=models.CharField(max_length=32),
        ),
    ]
